server:
  port: 8202 #服务端口

spring:
  application:
    name: service-cmn #服务名
  profiles:
    active: dev #环境设置：dev、test、prod
  datasource: #mysql数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis: #redis数据库连接
    database: 0
    host: localhost
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)


#设置指定路径的日志级别
logging:
  level:
    com.atguigu.yygh.cmn.mapper: DEBUG