server:
  port: 8201 #服务端口

spring:
  application:
    name: service-hosp #服务名
  profiles:
    active: dev #环境设置：dev、test、pro
  datasource: #mysql数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://192.168.112.127:27017/test

#设置指定路径的日志级别
logging:
  level:
    com.atguigu.yygh.hosp.mapper: DEBUG
    org.springframework.data.mongodb.core: DEBUG