server:
  port: 8160 #服务端口
spring:
  application:
    name: service-user #服务名
  profiles:
    active: dev #环境设置：dev、test、prod
  datasource: #mysql数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis: #redis数据库连接
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1800000
    lettuce:
      pool: #redis连接池
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: -1
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery: #nacos服务地址
        server-addr: 127.0.0.1:8848
#二维码登录
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/admin/user/wx/redirectProcessor

#sql语句日志打印
logging:
  level:
    com.atguigu.yygh.user.mapper: DEBUG