server:
  port: 8205 #服务端口
spring:
  application:
    name: service-oos #服务名
  profiles:
    active: dev #环境设置：dev、test、prod
  servlet:
    multipart: #上传的文件大小限制
      max-file-size: 1024MB
      max-request-size: 1024MB
