server:
  port: 8206 #服务端口
spring:
  application:
    name: service-sms #服务名
  profiles:
    active: dev #环境设置：dev、test、prod
  redis: #redis数据库连接
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1800000
    lettuce:
      pool: #redis连接池
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: -1
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery: #nacos服务地址
        server-addr: 127.0.0.1:8848